### ISSUE TITLE
Simple dashboard example for Grafana

### ISSUE THREAD

**Issue by GordonFreemanK** [xperimental/netatmo-exporter#12]
Hi!

I've created a simple dashboard for Grafana using the data from the docker image (https://hub.docker.com/r/xperimental/netatmo-exporter).
https://grafana.com/grafana/dashboards/13672

Feel free to copy it or reference directly if you want to link in the readme.

**Comment by xperimental** [comment]
Thanks for the contribution, I've added a link to the dashboard in the readme.

I have a few suggestions for improvements to the dashboard:

- Provide a variable to select the `station` to display, in case the user has more than one.
- Use aggregations on the queries, so that you really only get one series for each `module` if that is what you want to display, for example `avg(netatmo_sensor_temperature_celsius) by (module)` for the temperature panel. This avoids having multiple series or non-contiguous series in case a different label changes, for example due to an IP change on the exporter.
- In my version of the dashboard I have thresholds set on panels where there are "known-good" values. In the CO2 panel I have marked < 1000ppm as green and > 2000ppm as red and in the humidity panel I have set values < 40% and > 60% as yellow.

**Comment by SnorreSelmer** [comment]
@GordonFreemanK Atmospheric pressure is given in millibars (mBar), so multiply that graph query by 1000 and adjust unit accordingly. ;)
While standard atmospheric pressure at sea-level is technically 1.01325 Bar, it's always given as 1013.25 mBar.

**Comment by SnorreSelmer** [comment]
So, apparently Grafana is being "logical" about atmospheric pressure, so it will _always_ convert 1000 millibar to 1 bar. So to get proper display here, you have to label the graph "millibars" and set the unit to "none"...
