### ISSUE TITLE
Provide default location for token file in Docker image

### ISSUE THREAD

**Issue by SnorreSelmer** [xperimental/netatmo-exporter#52]
Maybe it already has, and it's just not documented, but a default folder to mount as a volume would be nice.

**Comment by xperimental** [comment]
The [default configuration](https://github.com/xperimental/netatmo-exporter/blob/master/internal/config/config.go#L40) has no default path for the token file. This is on purpose, because the location of the file very much depends on how and where the exporter is running. I have seen that a few people just set this to `token.json` putting it in the working directory of the exporter, which _can_ be a valid configuration and is the one I use for testing during development, but I don't see this as a working configuration for example for a deployment as a SystemD service. It would make more sense to have it in, for example, `/var/lib/netatmo-exporter` then.

I agree that the Docker image should provide a sensible default value and map it to a volume, because we can provide a "recommended configuration" there. And that's why the image does just that and sets the path to `/var/lib/netatmo-exporter/netatmo-token.json` and defines it as a volume ([code](https://github.com/xperimental/netatmo-exporter/blob/master/Dockerfile#L32-L33)).

I agree that it is not properly documented :slightly_smiling_face:

**Comment by xperimental** [comment]
Updated the readme with a mention of the default: https://github.com/xperimental/netatmo-exporter/commit/b98bb8a2bf49f8c67b43dc68e76b0c547cd44d46
