### ISSUE TITLE
Write token file upon refresh

### ISSUE THREAD

**Issue by RichieB2B** [xperimental/netatmo-exporter#54]
I just started using the new OAuth using the toke file. It works great, thanks!
I did notice however that the token file is only written when netatmo-explorer exists. I think it would be better to save the new tokens every time they are refreshed. In case of a crash the new tokens are currently lost.

**Comment by xperimental** [comment]
Currently the token rotation is completely handled by the `oauth` library I use, so the "netatmo-exporter code" does not know when a refresh actually happens, it is completely transparent to it. It just reads the (possibly changed) token from the library on exit.

Saving the token on change / periodically is something I had thought about before as well, but did not get to implementing so far.

**Comment by RichieB2B** [comment]
Perhaps you can check if the `expiry` has changed and only save the token file when it has. Once every few minutes should be enough.

**Comment by xperimental** [comment]
@RichieB2B Just realized something: I think the more important question for me is: why did it crash? Do you have any logs of the crash that we can use to fix that issue?

**Comment by RichieB2B** [comment]
netatmo-exporter doesn't crash often, the last time was 6 months and many versions ago. Not worth investigating now. It's just that you can't count on a clean process exit 100% of the time.

**Comment by xperimental** [comment]
Ok. I thought this occurred to you because of a recent crash and was worried there might be a bigger issue here than just "does not save token". :relieved: 

I do know that there's no "100% stable" but I surely try to make it as reliable as possible :slightly_smiling_face:

**Comment by xperimental** [comment]
It looks to me as if more people are experiencing errors writing the token file on shutdown (see mentioned issue).

I have come around to implementing a "save on token change" mechanism, but I am still looking at how to integrate this into the existing code. The token handling is done in the `oauth2` library and not my own code, so I'll have to move around a few bits first.

**Comment by szermatt** [comment]
I have the same problem, usually caused by power outages, which are unfortunately very common.

I fixed it for now with the following (draft) changes:
https://github.com/xperimental/netatmo-api-go/compare/master...szermatt:netatmo-api-go:savetoken
https://github.com/xperimental/netatmo-exporter/compare/master...szermatt:netatmo-exporter:savetoken

It modifies your copy of netatmo-api-go; I couldn't see an alternative. I do wonder whether it wouldn't be more straightforward to just do the auth2 stuff inside netatmo-exporter. 

I was getting ready to send them out, but you're already working on it, so I just thought I'd send them out FYI. Feel free to disregard them completely, to copy from  them, or, if you prefer, let me know if I should clean them up and sent them out pull request for a real review. 

Thanks!

**Comment by xperimental** [comment]
@szermatt Thanks for the contribution. I'm currently on vacation, but I'll have a look once I'm back home.

**Comment by xperimental** [comment]
Finally found the time to get this in.

Please have a look at the PR and test if this works properly. There's also a testing image available:

```
ghcr.io/xperimental/netatmo-exporter:save-token
```

**Comment by RichieB2B** [comment]
I've been running this version since this morning and it working great. It updates the storen JSON every hour.
